# Generated by Django 5.2.4 on 2025-07-30 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Área',
                'verbose_name_plural': 'Áreas',
                'ordering': ['sede', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Licencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('perpetua', 'Perpetua'), ('anual', 'Anual'), ('mensual', 'Mensual'), ('otro', 'Otro')], default='perpetua', max_length=20)),
                ('proveedor', models.CharField(blank=True, max_length=200, null=True)),
                ('fecha_adquisicion', models.DateField(blank=True, null=True)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cantidad_licencias', models.IntegerField(default=1)),
                ('activo', models.BooleanField(default=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Licencia',
                'verbose_name_plural': 'Licencias',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Sede',
                'verbose_name_plural': 'Sedes',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='producto',
            name='antivirus',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='producto',
            name='antivirus_nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='codigo_alquiler',
            field=models.CharField(blank=True, help_text='Código de alquiler si es alquilado', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='sistema_operativo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='tipo_propiedad',
            field=models.CharField(choices=[('propio', 'Propio'), ('alquilado', 'Alquilado')], default='propio', max_length=20),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='area_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_destino', to='inventario.area'),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='area_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_origen', to='inventario.area'),
        ),
        migrations.AddField(
            model_name='producto',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='inventario.area'),
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('cargo', models.CharField(blank=True, max_length=100, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal', to='inventario.area')),
            ],
            options={
                'verbose_name': 'Personal',
                'verbose_name_plural': 'Personal',
                'ordering': ['apellido', 'nombre'],
            },
        ),
        migrations.AddField(
            model_name='movimiento',
            name='personal_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_destino', to='inventario.personal'),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='personal_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_origen', to='inventario.personal'),
        ),
        migrations.AddField(
            model_name='producto',
            name='personal_asignado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos_asignados', to='inventario.personal'),
        ),
        migrations.CreateModel(
            name='ProductoLicencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('licencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.licencia')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.producto')),
            ],
            options={
                'verbose_name': 'Licencia de Producto',
                'verbose_name_plural': 'Licencias de Productos',
                'unique_together': {('producto', 'licencia')},
            },
        ),
        migrations.AddField(
            model_name='producto',
            name='licencias',
            field=models.ManyToManyField(blank=True, through='inventario.ProductoLicencia', to='inventario.licencia'),
        ),
        migrations.AddField(
            model_name='area',
            name='sede',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='inventario.sede'),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='sede_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_destino', to='inventario.sede'),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='sede_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_origen', to='inventario.sede'),
        ),
        migrations.AddField(
            model_name='producto',
            name='sede',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='inventario.sede'),
        ),
        migrations.AlterUniqueTogether(
            name='area',
            unique_together={('nombre', 'sede')},
        ),
    ]
