# Generated by Django 5.2.4 on 2025-07-31 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_area_licencia_sede_producto_antivirus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='fecha_alquiler',
            field=models.DateField(blank=True, help_text='Fecha de inicio del alquiler', null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='fecha_vencimiento_alquiler',
            field=models.DateField(blank=True, help_text='Fecha de vencimiento del alquiler', null=True),
        ),
    ]
