# Generated by Django 5.2.4 on 2025-07-31 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_producto_fecha_alquiler_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='licencia',
            name='licencias_disponibles',
            field=models.IntegerField(default=1, help_text='Cantidad de licencias disponibles para asignar'),
        ),
        migrations.AddField(
            model_name='licencia',
            name='tipo_distribucion',
            field=models.CharField(choices=[('oem', 'OEM'), ('retail', 'Retail'), ('volume', 'Volume License'), ('otro', 'Otro')], default='retail', max_length=20, verbose_name='Tipo de Distribución'),
        ),
    ]
