# Generated by Django 5.2.4 on 2025-07-31 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_licencia_clave_licencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre descriptivo de la cuenta', max_length=200)),
                ('tipo_cuenta', models.CharField(choices=[('office365', 'Office 365'), ('google', 'Google Workspace'), ('aws', 'Amazon Web Services'), ('azure', 'Microsoft Azure'), ('dropbox', 'Dropbox'), ('slack', 'Slack'), ('zoom', 'Zoom'), ('adobe', 'Adobe Creative Cloud'), ('otro', 'Otro')], default='office365', max_length=20, verbose_name='Tipo de Cuenta')),
                ('email', models.EmailField(help_text='Correo electrónico de la cuenta', max_length=254)),
                ('usuario', models.CharField(help_text='Nombre de usuario', max_length=100)),
                ('password', models.TextField(blank=True, help_text='Contraseña encriptada', null=True)),
                ('url_acceso', models.URLField(blank=True, help_text='URL de acceso a la plataforma', null=True)),
                ('fecha_creacion_cuenta', models.DateField(blank=True, help_text='Fecha de creación de la cuenta', null=True)),
                ('fecha_vencimiento', models.DateField(blank=True, help_text='Fecha de vencimiento de la suscripción', null=True)),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('inactiva', 'Inactiva'), ('suspendida', 'Suspendida'), ('vencida', 'Vencida')], default='activa', max_length=20)),
                ('plan_suscripcion', models.CharField(blank=True, help_text='Plan o tipo de suscripción', max_length=100, null=True)),
                ('costo_mensual', models.DecimalField(blank=True, decimal_places=2, help_text='Costo mensual de la suscripción', max_digits=10, null=True)),
                ('proveedor', models.CharField(blank=True, help_text='Proveedor del servicio', max_length=200, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cuentas', to='inventario.area')),
                ('personal_asignado', models.ForeignKey(blank=True, help_text='Personal asignado a esta cuenta', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cuentas_asignadas', to='inventario.personal')),
                ('sede', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cuentas', to='inventario.sede')),
            ],
            options={
                'verbose_name': 'Cuenta',
                'verbose_name_plural': 'Cuentas',
                'ordering': ['tipo_cuenta', 'nombre'],
            },
        ),
    ]
