# Generated by Django 5.2.4 on 2025-08-01 21:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_cuenta'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanificacionSemanal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Título de la tarea', max_length=200)),
                ('descripcion', models.TextField(help_text='Descripción detallada de la tarea')),
                ('dia_semana', models.CharField(choices=[('lunes', 'Lunes'), ('martes', 'Martes'), ('miercoles', 'Miércoles'), ('jueves', 'Jueves'), ('viernes', 'Viernes'), ('sabado', 'Sábado'), ('domingo', 'Domingo')], help_text='Día de la semana', max_length=20)),
                ('hora_inicio', models.TimeField(help_text='Hora de inicio')),
                ('hora_fin', models.TimeField(blank=True, help_text='Hora de finalización', null=True)),
                ('prioridad', models.CharField(choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], default='media', max_length=10)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En Proceso'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('fecha_completada', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='inventario.area')),
                ('personal_asignado', models.ForeignKey(blank=True, help_text='Personal asignado a esta tarea', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas_asignadas', to='inventario.personal')),
                ('sede', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='inventario.sede')),
            ],
            options={
                'verbose_name': 'Planificación Semanal',
                'verbose_name_plural': 'Planificaciones Semanales',
                'ordering': ['dia_semana', 'hora_inicio', 'prioridad'],
            },
        ),
        migrations.CreateModel(
            name='ConexionWinbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre descriptivo de la conexión', max_length=200)),
                ('tipo_equipo', models.CharField(choices=[('router', 'Router'), ('switch', 'Switch'), ('access_point', 'Access Point'), ('firewall', 'Firewall'), ('otro', 'Otro')], default='router', max_length=20, verbose_name='Tipo de Equipo')),
                ('ip_address', models.GenericIPAddressField(help_text='Dirección IP del equipo')),
                ('puerto', models.IntegerField(default=8291, help_text='Puerto Winbox (por defecto 8291)')),
                ('usuario', models.CharField(help_text='Usuario de acceso', max_length=100)),
                ('password', models.TextField(blank=True, help_text='Contraseña encriptada', null=True)),
                ('ubicacion_fisica', models.CharField(blank=True, help_text='Ubicación física del equipo', max_length=200, null=True)),
                ('modelo', models.CharField(blank=True, max_length=100, null=True)),
                ('serie', models.CharField(blank=True, max_length=100, null=True)),
                ('version_routeros', models.CharField(blank=True, help_text='Versión de RouterOS', max_length=50, null=True)),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('inactiva', 'Inactiva'), ('mantenimiento', 'En Mantenimiento'), ('error', 'Error de Conexión')], default='activa', max_length=20)),
                ('ultima_conexion', models.DateTimeField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conexiones_winbox', to='inventario.area')),
                ('sede', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conexiones_winbox', to='inventario.sede')),
                ('ultimo_usuario_conectado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conexiones_realizadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conexión Winbox',
                'verbose_name_plural': 'Conexiones Winbox',
                'ordering': ['sede', 'area', 'nombre'],
                'unique_together': {('ip_address', 'puerto')},
            },
        ),
    ]
